# Generated by Django 4.2.3 on 2023-07-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Identifiers',
        ),
    ]
