# Generated by Django 4.2.3 on 2023-07-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0002_delete_identifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='created',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lcclassification',
            name='book',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Created',
        ),
        migrations.DeleteModel(
            name='LCClassification',
        ),
    ]
