# Generated by Django 4.2.3 on 2023-07-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_collection', '0003_remove_created_book_remove_lcclassification_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishplace',
            old_name='place',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subjectplace',
            old_name='place',
            new_name='name',
        ),
    ]
